#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Apr 18 23:25:46 EEST 2024
# SW Build 4081461 on Thu Dec 14 12:22:04 MST 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim top_tb_behav -key {Behavioral:topsim:Functional:top_tb} -tclbatch top_tb.tcl -log simulate.log"
xsim top_tb_behav -key {Behavioral:topsim:Functional:top_tb} -tclbatch top_tb.tcl -log simulate.log

