#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Mar 23 11:18:25 EET 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim top_tb_func_impl -key {Post-Implementation:topsim:Functional:top_tb} -tclbatch top_tb.tcl -log simulate.log"
xsim top_tb_func_impl -key {Post-Implementation:topsim:Functional:top_tb} -tclbatch top_tb.tcl -log simulate.log

